-- schema.sql

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Table: words
create table if not exists public.words (
    id bigint generated by default as identity primary key,
    word text not null unique,
    meaning text not null,
    phonetic text,
    examples jsonb default '[]'::jsonb
);

-- Table: user_stats
create table if not exists public.user_stats (
    user_id uuid references auth.users not null primary key,
    streak integer default 0,
    last_study_date timestamp with time zone,
    xp integer default 0
);

-- Table: user_progress
create table if not exists public.user_progress (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    word_id bigint references public.words not null,
    interval integer default 0,
    repetition integer default 0,
    ease_factor real default 2.5,
    next_review_date timestamp with time zone default now(),
    unique(user_id, word_id)
);

-- Setup logic for RLS (Row Level Security)
alter table public.words enable row level security;
alter table public.user_stats enable row level security;
alter table public.user_progress enable row level security;

-- Policies for words (everyone can read)
create policy "Allow public read access to words"
on public.words for select to public using (true);

-- Policies for user_stats (users can read and update their own)
create policy "Users can view own stats"
on public.user_stats for select to authenticated using (auth.uid() = user_id);

create policy "Users can update own stats"
on public.user_stats for update to authenticated using (auth.uid() = user_id);

create policy "Users can insert own stats"
on public.user_stats for insert to authenticated with check (auth.uid() = user_id);

-- Policies for user_progress (users can manage their own progress)
create policy "Users can view own progress"
on public.user_progress for select to authenticated using (auth.uid() = user_id);

create policy "Users can update own progress"
on public.user_progress for update to authenticated using (auth.uid() = user_id);

create policy "Users can insert own progress"
on public.user_progress for insert to authenticated with check (auth.uid() = user_id);
